import type { Metadata } from 'next';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <Header />
        <main className="w-full flex justify-center max-w-screen-xl mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
